########## TOP LEVEL SIM SETUP ##########
casename: falcon_Ez
meshfile: '../mesh/falconfine'     # No file extension
case_select: 'Ez'

########## SOLVER PARAMS ##########
outdir: 'out/'
process_mesh: True
buildAF: True
compute_sol: True
call_pv: False

ndim: 3
porder: &porder 2
solver: 'gmres'
solver_tol: 1e-7

visorder: *porder
viz_labels:
    scalars:
        0: Potential
    vectors:
        0: Potential Gradient

########## GEOMETRY SETUP ##########
scale_factor: 1.0 

########## BOX SURFACE INDICES ##########
x_minus_face_index: 1
x_plus_face_index: 2
y_minus_face_index: 3
y_plus_face_index: 4
z_minus_face_index: 5
z_plus_face_index: 6
surface_index: 7

########## PHYSICS PARAM ##########
phys_param:
    kappa: 1
    c: [0, 0, 0]
    s: 0