########## TOP LEVEL SIM SETUP ##########
casename: E190_430K_Ey
meshfile: '../mesh/boeing_plane_final_coarse'     # No file extension
case_select: 'Ey'

########## SOLVER PARAMS ##########
outdir: 'out/'
process_mesh: True
buildAF: True
compute_sol: True
call_pv: False

ndim: 3
porder: &porder 2
solver: 'gmres'
solver_tol: 1e-7

visorder: *porder
viz_labels:
    scalars:
        0: Potential
    vectors:
        0: Potential Gradient

surf_viz_labels:
    scalars:
        0: Surface Potential
        1: Surface Normal Electric Field
    vectors:

########## GEOMETRY SETUP ##########
fuselage_dia: 3.01     # This is the diameter of the fuselage of the E190 in m: https://modernairliners.com/embraer-e-jet-specs/

fuselage_pts: 
    0: [8547.42, 1505.00, 5678.37]
    1: [8547.42, -1505.00, 5678.37]

########## BOX SURFACE INDICES ##########
x_minus_face_index: 138
x_plus_face_index: 139
y_minus_face_index: 140
y_plus_face_index: 141
z_minus_face_index: 142
z_plus_face_index: 143

########## PHYSICS PARAM ##########
phys_param:
    kappa: 1
    c: [0, 0, 0]
    s: 0